<?php

/**
 * @file
 * Contains delicious_paragraphs_jumbotron.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function delicious_paragraphs_jumbotron_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the delicious_paragraphs_jumbotron module.
    case 'help.page.delicious_paragraphs_jumbotron':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paragraph type based on a Bootstrap Jumbotron.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function delicious_paragraphs_jumbotron_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__dp_jumbotron' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_jumbotron_button_link__dp_jumbotron' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_jumbotron_headline__dp_jumbotron' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_jumbotron_message__dp_jumbotron' => [
      'base hook' => 'paragraph',
    ],
  ];
}
