<?php

/**
 * @file
 * Contains dp_media_row.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dp_image_text_row_row_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dp_media_row module.
    case 'help.page.dp_media_row':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paragraph that displays an image with associated text.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dp_image_text_row_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__dp_image_text_row' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_image_text_row_text__dp_image_text_row' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_image_text_row_heading__dp_image_text_row' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_image_text_row_image__dp_image_text_row' => [
      'base hook' => 'paragraph',
    ],
  ];
}
