<?php

/**
 * @file
 * Contains delicious_paragraphs_logo_row.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function delicious_paragraphs_logo_row_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the delicious_paragraphs_logo_row module.
    case 'help.page.delicious_paragraphs_logo_row':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paragraph to show a row of logos or other images.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function delicious_paragraphs_logo_row_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__dp_logo_row' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dp_logo_row_logo' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_logo_row_heading__dp_logo_row' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_logo_row_logos__dp_logo_row' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_logo_row_footer__dp_logo_row' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_dp_logo_row_logo_image__dp_logo_row_logo' => [
      'base hook' => 'paragraph',
    ],
  ];
}
